distancias de picado, qué maleducado
gbandres98/earthshapers pull request #7
Opened 2021-02-24 23:42 UTC by AntonioLoFu

2021-02-24 23:49 UTC, gbandres98 requested changes
Tonterías de que soy muy pesado perdón

2021-02-24 23:49 UTC, gbandres98 commented on Assets/Scripts/BaseCharacter.cs
> +
Quita estos espacios nuevos pls

2021-02-24 23:49 UTC, gbandres98 commented on Assets/Scripts/BaseCharacter.cs
> +        Debug.Log(MouseNotInCharacterRange());
Se han quedado los mensajes de debug

2021-02-24 23:49 UTC, gbandres98 commented on Assets/Scripts/BaseCharacter.cs
> +    public double DistanceToThecursor()
Esta función no se usa

2021-02-24 23:49 UTC, gbandres98 commented on Assets/Scripts/BlockManager.cs
> +
Estos cambios de espacios mejor no meterlos si no cambias nada más en el archivo, que pueden dar conflictos

2021-02-25 11:46 UTC, CMarah commented
@AntonioLoFu Creo que aún te faltan algunas espacios en blanco de los que ha dicho Jukes por quitar, en BaseCharacters y BlockManager

2021-02-25 11:53 UTC, AntonioLoFu commented
> @AntonioLoFu Creo que aún te faltan algunas espacios en blanco de los que ha dicho Jukes por quitar, en BaseCharacters y BlockManager

Es que en vs no me sale cuales he metido yo y cuales venían del pull, si pudiéramos mirar un formateador de código para que lo usemos todos estaría del carajo para no tener que quitar esas cosa a mano.

2021-02-25 14:04 UTC, gbandres98 approved these changes

2021-02-25 14:04 UTC, gbandres98 commented
Buena toni gracias

2021-02-25 14:04 UTC, merged